### ISSUE TITLE
Review and merge L2 test cases for RMF AudioCapture HAL

### ISSUE THREAD

**Issue by chaithents** [rdkcentral/rdk-halif-test-rmf_audio_capture#6]
I've raised a PR https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/pull/5 with the changes. L2 test cases were reviewed a few rounds previously, but wasn't merged into the old comcast-sky repo as focus was on shipping L1 first.

**Comment by Ulrond** [comment]
https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/pull/4/files#diff-cfbf2cf5c46f28c9994f07c4d9430995ba31f357d54ce87b92180ddd4780adbf this conflicts with the documentation from here..
