### ISSUE TITLE
VTS L1 Enhancement - Test Profile Changes - RMF Audio Capture

### ISSUE THREAD

**Issue by akhilbhas** [rdkcentral/rdk-halif-test-rmf_audio_capture#9]
This task is to modify the L1 concerning the latest Test profile changes if any. If there are no changes concerning the test profile, this Jira can be closed with proper information.

Interface file:
https://github.com/rdkcentral/rdk-halif-rmf_audio_capture/blob/main/include/rmfAudioCapture.h

L1 File:
https://github.com/rdkcentral/rdk-halif-test-rmf_audio_capture/blob/main/src/test_l1_rmfAudioCapture.c

**Comment by thanushreevani** [comment]
there is no test profile added for this module except rmfAudioCaptureExtendedEnumsNotSupported.yml so closing this issue

**Comment by srinivasgtl** [comment]
New test profiles added for the rmf audio capture

**Comment by srinivasgtl** [comment]
All changes are now available at tag 1.3.1
